### ISSUE TITLE
mirdata.guitarset.load() is slow

### ISSUE THREAD

**Issue by tomxi** [mir-dataset-loaders/mirdata#118] opened 2019-08-28 01:14 UTC
Right now it takes about 40 seconds for me to run `mirdata.guitarset.validate(data_home=DATAHOME)`.... I feel like this is not normal...

```
%time mirdata.guitarset.validate(DATA_HOME, silence=False)

CPU times: user 30 s, sys: 8.58 s, total: 38.5 s
Wall time: 44.8 s
({}, {})
```

This is causing guitarset.load() to be very slow.

**Comment by magdalenafuentes** [comment] 2019-08-30 15:50
I think that's the idea of the `silence` flag in the `validator`, though right now it's only skipping the [messages printing it seems?](https://github.com/mir-dataset-loaders/mirdata/blob/13c0bec56df1f16ccbea541ef846155a135c7c29/mirdata/utils.py#L89-L109) is this the expected behaviour @rabitt?

**Comment by rabitt** [comment] 2019-09-04 13:42
@magdalenafuentes Yep, that's the intended behavior. I'm OK with adding a `skip_validation` flag to dataset.load, which defaults to `True` to speed things up for repeated use cases. What do you think?

**Comment by rabitt** [comment] 2019-09-13 15:58
I opened #127 to address this larger issue. Closing this one!

**Closed by rabitt** 2019-09-13 15:58 UTC
